(()=>{'use strict';
const $=id=>document.getElementById(id), state={items:[],selected:null,reads:[],errors:[],last:null};
const safe=(s)=>String(s??'');const stamp=()=>new Date().toLocaleTimeString('pt-BR');const log=(s)=>{const el=$('terminal');el.textContent+='['+stamp()+'] '+s+'\n';el.scrollTop=el.scrollHeight;};
function clear(id){$(id).replaceChildren()}
function add(id,tag,text,cls){const e=document.createElement(tag);e.textContent=text;if(cls)e.className=cls;$(id).append(e);return e}
function dateOf(x){let value=x.published;if(typeof value==='string'&&!Number.isNaN(Date.parse(value)))return new Date(value);return null}
function image(id,url){clear(id);if(typeof url!=='string'||!/^https?:\/\/|^\.\.?\//i.test(url)){add(id,'span','Sem imagem vinculada');return}const pic=document.createElement('img');pic.alt=id==='art'?'Arte da matéria':'Foto original da matéria';pic.loading='lazy';pic.referrerPolicy='no-referrer';pic.onerror=()=>{clear(id);add(id,'span','Imagem indisponível');log('Falha ao carregar imagem: '+id)};pic.src=url;$(id).append(pic)}
function selected(){return state.items.find(x=>x.id===state.selected)||state.items[0]}
function stage(label,verified){const e=add('steps','span',label+(verified?' ✓':' · não verificado'),'step '+(verified?'yes':'unknown'));e.title=verified?'Confirmado pelos dados da matéria':'Sem confirmação independente'}
function renderSelection(){const n=selected();$('title').textContent=n?.title||'Nenhuma matéria';$('meta').textContent=n?[n.category,n.date,n.credit].filter(Boolean).join(' · '):'';$('caption').textContent=n?.caption||n?.summary||'Sem legenda registrada';image('art',n?.instagramImage);image('source',n?.sourceImage||n?.image);clear('steps');stage('Portal',!!n&&n.published===true);stage('Feed',!!n?.feedPublishedAt);stage('Story',!!n?.storyPublishedAt);stage('Reel',!!n?.reelPublishedAt)}
function renderLists(){clear('queue');clear('history');const queue=state.items.filter(x=>x.published!==true);const history=state.items.filter(x=>x.published===true);if(!queue.length)add('queue','p','Nenhuma matéria pendente identificada no news.json','mut');queue.slice(0,30).forEach(x=>{let b=add('queue','button',x.title||x.id||'Sem título','item'+(x.id===state.selected?' active':''));b.type='button';b.onclick=()=>{state.selected=x.id;renderSelection();renderLists()}});if(!history.length)add('history','p','Nenhum registro confirmado','mut');history.slice(0,30).forEach(x=>{let b=add('history','button',x.title||x.id||'Sem título','item'+(x.id===state.selected?' active':''));b.type='button';b.onclick=()=>{state.selected=x.id;renderSelection();renderLists()}})}
function service(name,value,detail,cls){const row=add('services','div','','row');const a=document.createElement('span'),b=document.createElement('span');a.textContent=name;b.textContent=value;b.className=cls||'mut';b.title=detail;row.append(a,b)}
function alert(s){add('alerts','div',s,'alert')}
function metrics(){const list=state.items,total=list.length,arts=list.filter(x=>!!x.instagramImage).length,published=list.filter(x=>x.published===true).length,pending=list.filter(x=>x.published!==true).length;clear('services');clear('alerts');service('Leitura news.json',state.last?'Disponível':'Falhou','Resposta HTTP e JSON validados',state.last?'ok':'bad');service('Matérias',String(total),'Quantidade de entradas válidas');service('Portal sinalizado',total?Math.round(published/total*100)+'%':'—','Somente campo published === true');service('Arte vinculada',total?Math.round(arts/total*100)+'%':'—','Presença de URL, sem garantia da imagem carregar');service('Fila identificada',String(pending),'Ausência de published === true');service('Feed / Story / Reel','Não verificado','Sem fonte autenticada de status de publicação');service('GitHub Actions','Não verificado','Verifique execuções no link do GitHub');$('health').textContent=state.last?'news.json acessível':'Leitura indisponível';$('health').className=state.last?'big ok':'big bad';$('basis').textContent='Cobertura de arte: '+(total?Math.round(arts/total*100)+'%':'—')+' · Portal sinalizado: '+(total?Math.round(published/total*100)+'%':'—');$('healthbar').style.width=(total?Math.round(arts/total*100):0)+'%';if(!state.last)alert('Falha na leitura dos dados. Consulte o diagnóstico e tente atualizar.');if(pending)alert(pending+' matéria(s) sem confirmação de publicação no portal.');if(state.errors.length)alert(state.errors.length+' erro(s) registrado(s) nesta sessão.');if(!pending&&!state.errors.length&&state.last)alert('Leitura sem erros locais. Instagram e automações ainda exigem verificação independente.');const points=state.reads.map((v,i)=>((i*280)/Math.max(1,state.reads.length-1)).toFixed(1)+','+(90-v*.8).toFixed(1)).join(' ');$('line').setAttribute('points',points);$('chart').setAttribute('aria-label','Últimas '+state.reads.length+' leituras; 100 indica acesso ao JSON');$('diagnostics').textContent='Última leitura: '+(state.last?state.last.toLocaleString('pt-BR'):'nenhuma')+'\nRegistros: '+total+'\nErros locais: '+state.errors.length+'\nFonte: ../data/news.json\nStatus social: indisponível sem API autenticada'}
async function refresh(){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);$('updated').textContent='Consultando…';try{const r=await fetch('../data/news.json?ts='+Date.now(),{cache:'no-store',signal:controller.signal});if(!r.ok)throw Error('HTTP '+r.status);const data=await r.json();if(!Array.isArray(data))throw Error('Formato inválido: esperada lista');state.items=data.filter(x=>x&&typeof x==='object'&&!Array.isArray(x));state.last=new Date();if(!state.items.some(x=>x.id===state.selected))state.selected=state.items[0]?.id||null;state.reads.push(100);log('news.json: '+state.items.length+' registros lidos');$('updated').textContent='Atualizado às '+stamp();renderSelection();renderLists()}catch(e){state.reads.push(0);state.last=null;state.errors.push(safe(e.message));log('ERRO '+safe(e.message));$('updated').textContent='Falha de leitura';}finally{clearTimeout(timer);state.reads=state.reads.slice(-20);metrics()}}
document.addEventListener('error',e=>{if(e.target?.tagName==='IMG')return;state.errors.push(safe(e.message||'Erro de recurso'));log('ERRO de recurso');metrics()},true);
window.addEventListener('error',e=>{state.errors.push(safe(e.message));log('ERRO JavaScript: '+safe(e.message));metrics()});
window.addEventListener('unhandledrejection',e=>{state.errors.push(safe(e.reason));log('ERRO assíncrono: '+safe(e.reason));metrics()});
$('refresh').onclick=refresh;$('cmd').onsubmit=e=>{e.preventDefault();const cmd=$('command').value.trim().toLowerCase();$('command').value='';if(!cmd)return;log('> '+cmd);if(cmd==='ajuda')log('Comandos: ajuda, status, fila, erros, atualizar, limpar');else if(cmd==='status')log('JSON: '+(state.last?'acessível':'falhou')+' | '+state.items.length+' matérias | redes sociais não verificadas');else if(cmd==='fila')log(state.items.filter(x=>x.published!==true).length+' matérias sem published === true');else if(cmd==='erros')log(state.errors.length?state.errors.join(' | '):'Nenhum erro local nesta sessão');else if(cmd==='atualizar')refresh();else if(cmd==='limpar')$('terminal').textContent='';else log('Comando desconhecido. Digite ajuda. Nenhuma ação externa foi executada.')};log('Monitor inicializado. Comandos locais de consulta.');refresh();setInterval(refresh,60000);
})();